title: Alfie Richards
author:
  name: Alfie Richards
  email: main@alfierichards.com
description: >
    This is my website to present information about myself and to host my out of date CV.
    It will mostly be used as somewhere to point people on my social medias and on my CV.

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%d %b, %Y"

  # generate social links in footer
  social_links:
    github:  AlfGalf
    instagram: alfiejjrichards
    linkedin: alfie-richards2

    # Mastodon instances
    mastodon:
    - username: alfier
      instance: mstdn.social

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - index.md

exclude: [Gemfile, Gemfile.lock, .gitignore, .git]
